### ISSUE TITLE
secure random

### ISSUE THREAD

**Issue by adrelanos** [mirage/xentropyd#12]
Please have a look.

https://www.av8n.com/computer/htm/secure-random.htm

He suggest to feed randomness a lot earlier to really fix the security issue.

**Comment by pqwy** [comment]
A lot earlier than what? Which security issue?

**Comment by adrelanos** [comment]
Under https://www.av8n.com/computer/htm/secure-random.htm#sec-discuss he explains, that the kernel requires randomness even before init / upstart / systemd has been started.

He makes a case for Storing a Seed in the Boot Image.

https://www.av8n.com/computer/htm/secure-random.htm#sec-boot-image

**Comment by pqwy** [comment]
Please divert further discussion to the official mailing list of the MirageOS project: mirageos-devel@lists.xenproject.org .

Thanks!
